replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/pk-sandbox-507311/travelbooking/booking-service
  tag: "bc551cc45f84d19ea629c4df5a1a6447c1f9f31e"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8083

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  DB_HOST: "postgresql-booking"
  DB_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "booking-service"
