replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/pk-sandbox/travelbooking/notification-service
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8085

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  DB_HOST: "postgresql-notification"
  DB_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "notification-service"
