replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/pk-sandbox-507311/travelbooking/frontend
  tag: "bc551cc45f84d19ea629c4df5a1a6447c1f9f31e"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
