replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/pk-sandbox-507311/travelbooking/frontend
  tag: "0982e42c1e1202502fec30928711695c4892bfd4"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
