replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/pk-sandbox-507311/travelbooking/search-service
  tag: "bc551cc45f84d19ea629c4df5a1a6447c1f9f31e"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3002

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  PORT: "3002"
  DB_HOST: "postgresql-search"
  DB_PORT: "5432"
  DB_NAME: "searchdb"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  JWT_SECRET: "supersecret"
  USER_SERVICE_URL: "http://user-service:3001"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
  NODE_ENV: "development"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "search-service"
