apiVersion: v2
name: jaeger
description: Distributed Tracing
type: application
version: 0.1.0
dependencies:
  - name: jaeger
    version: "3.4.1"
    repository: https://jaegertracing.github.io/helm-charts
