apiVersion: v2
name: monitoring
description: Prometheus + Grafana + Alertmanager
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "65.1.0"
    repository: https://prometheus-community.github.io/helm-charts
