apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: travelbooking-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pkrhce/travelbooking-gitops.git
    targetRevision: main
    path: apps
    directory:
      exclude: 'app-of-apps.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
