apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: "3.4.1"
    helm:
      values: |
        provisionDataStore:
          cassandra: false
        allInOne:
          enabled: true
          ingress:
            enabled: false
        storage:
          type: memory
        collector:
          enabled: false
        query:
          enabled: false
        agent:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
