replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/pk-sandbox-507311/travelbooking/payment-service
  tag: "bd32858179bcdd909ea6176937b97f487e08d3a9"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3004

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  PORT: "3004"
  DB_HOST: "postgresql-payment"
  DB_PORT: "5432"
  DB_NAME: "paymentdb"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  JWT_SECRET: "supersecret"
  USER_SERVICE_URL: "http://user-service:3001"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
  NODE_ENV: "development"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "payment-service"
